In [1]:
import numpy as np
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

# inverse vector

In [3]:
Ainv = np.linalg.inv(A)
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

# to check inverse vector

In [4]:
Ainv.dot(A)

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [5]:
A.dot(Ainv)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

# determinant of matrix A

In [6]:
np.linalg.det(A)

-2.0000000000000004

# diagonal of matrix A

In [7]:
np.diag(A)

array([1, 4])

In [8]:
np.diag([1,2])

array([[1, 0],
       [0, 2]])

# inner and outer product of matrices

In [9]:
a = np.array([1,2])
b = np.array([3,4])

In [10]:
np.outer(a,b)

array([[3, 4],
       [6, 8]])

In [11]:
np.inner(a,b)

11

In [12]:
a.dot(b) # same as inner product

11

# diagonal sum and trace()

In [16]:
np.diag(A).sum() #diag requires two dimensional vector or matrix


5

In [15]:
np.trace(A)

5

# covariance of matrix

In [17]:
X = np.random.rand(100,3) #GUASSIAN random no.s # row gives 100 sample and col 3 gives three features

In [18]:
cov = np.cov(X)

In [20]:
cov.shape

(100, 100)

In [22]:
cov = np.cov(X.T)

In [23]:
cov.shape # to find covairnce of matrix, first transpose it

(3, 3)

# eigen matrix

In [24]:
np.linalg.eigh(cov) #as we know covariance is symmetric matrix we use eigh()

(array([0.06488725, 0.08356958, 0.09174965]),
 array([[-0.70804366, -0.2532152 ,  0.65920879],
        [-0.6842551 ,  0.476756  , -0.55181398],
        [-0.17455407, -0.84177537, -0.51082786]]))

In [25]:
np.linalg.eig(cov) # only regular eigen function


(array([0.06488725, 0.09174965, 0.08356958]),
 array([[ 0.70804366,  0.65920879,  0.2532152 ],
        [ 0.6842551 , -0.55181398, -0.476756  ],
        [ 0.17455407, -0.51082786,  0.84177537]]))