In [3]:
import numpy as np

In [7]:
M = np.array([[1,2],[3,4]])
L = [[1,2],[3,4]]


In [8]:
L[0]

[1, 2]

In [9]:
L[0][0]

1

In [10]:
M[0][0]

1

In [11]:
M[0,0]

1

In [13]:
M2 = np.matrix([[1,2],[3,4]])
M2

matrix([[1, 2],
        [3, 4]])

In [14]:
A = np.array(M2)
A

array([[1, 2],
       [3, 4]])

In [15]:
A.T

array([[1, 3],
       [2, 4]])

In [18]:
Z = np.zeros(10)
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
Y = np.zeros([10,10])
Y

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
A = np.ones((10,10))
A

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [23]:
R = np.random.random((10,10)) ## uniformly distributed number between 0 and 1
R

array([[0.4317768 , 0.92439689, 0.91270865, 0.96980885, 0.74003843,
        0.72304621, 0.03138753, 0.01871638, 0.63904165, 0.40570236],
       [0.68752827, 0.47562759, 0.79490874, 0.39192178, 0.3622783 ,
        0.03757973, 0.54772967, 0.7119338 , 0.22157288, 0.56757079],
       [0.95420395, 0.71318187, 0.78970987, 0.20263475, 0.15615051,
        0.22223678, 0.9758667 , 0.47272523, 0.7881541 , 0.33524606],
       [0.95648524, 0.17385957, 0.43700362, 0.95333186, 0.33159176,
        0.98896419, 0.45981598, 0.2931502 , 0.59801364, 0.63282126],
       [0.58895462, 0.40485258, 0.78328481, 0.36653993, 0.77061323,
        0.6854758 , 0.64674085, 0.92529311, 0.05448808, 0.55853288],
       [0.12423856, 0.87985491, 0.39485247, 0.72363201, 0.24903428,
        0.76423186, 0.26365573, 0.6471618 , 0.09619814, 0.58375451],
       [0.4313382 , 0.23920375, 0.52216576, 0.98201875, 0.48706963,
        0.43138801, 0.44256391, 0.49303787, 0.96209542, 0.91572687],
       [0.62010092, 0.25701546, 0.6418317

In [25]:
RG = np.random.randn(10,10)
RG  ##gaussian distribution with mean 0 and varaince 1

array([[-1.31388483,  0.86999736, -0.1933119 ,  0.39003193,  1.40438103,
         0.27267181,  0.95313592,  1.098642  ,  0.68322245,  0.45622281],
       [-0.42258934,  0.50428415, -0.38749131,  1.16140223, -0.42426383,
         0.02405929,  0.05312458,  0.48453051,  1.61148188, -0.1551056 ],
       [ 0.13789078, -0.10571322,  0.38431763, -1.80965056, -0.38908181,
        -1.82029068, -1.92730581, -1.82812524, -0.56625984,  0.61496014],
       [ 1.88900673, -0.46967294,  0.92013252, -2.1439459 ,  0.13953975,
         0.96166557, -2.13241495,  2.37821989, -0.01164528, -0.45134699],
       [ 0.09423578, -0.40620733, -0.35341588, -0.37055036, -0.86249488,
         0.20115842,  0.58275053,  1.31295934,  0.13597935, -1.89808755],
       [-0.96551604,  0.2284652 , -2.93618163, -1.76754464,  1.10756805,
        -0.6679099 , -0.48313344, -2.42896817,  1.75403859, -0.26074315],
       [ 0.42645772,  0.37946574,  1.81874428, -0.19038442,  0.69778391,
         0.21718738, -0.53338717, -0.68660614

In [26]:
RG.mean()

-0.004381525046720178

In [27]:
RG.var()

1.0406918173153954